whatsapp_api:
  business_id: "1019425660663203"
  phone_id: "1152154214647264"
  token: "EAAMfqZAxF00wBRhfAUjHbrz1GczazXZAU03fS7G0BTqJziVam1cclWRlQZBFQ4lfZBArJo6ZBVzlOfVjcQJP3ZBhoFQtNbW77JS2rB6SOq4FbvPDVLDrepNZB1fBKTk64mdQLSdvXfdJAvXe6qxwvXKctrbAJZAHUkmMzw8RZAxRIPtj82zWlLi34Df3DN5rwvSzGicalpixWCPNTKQG4tlMbvJ3xvZBNNfzF8EiTKUKmS6ZAbOnuMjj1KmRGUNsXgPUsyJpsMW4pJ2y6rh7i0ZCJEmN"
